apiVersion: v1
kind: Service
metadata:
    name: aca2pipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: aca2pipelinesjavascriptdocker